# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7166545d82bc4189ab7b864f5764d094e15a982e0385847ba822041d8886036918a64262f19c5e79bba54f043f50856b592182839493f1ad04a7cc23df2e1ba6

test:
  secret_key_base: 20f319fb4bb023eb08ab25e5f3d73e92cb9c2d3c17270f5db1ee1ecd6485dcbc6031bea3c201c884a3d83ee3347c7276e653449c266a89cef4252aecba1848e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
